FROM quay.io/kairos/kairos-init:v0.14.0@sha256:f9cbde8dd9f7a6c29920a55ef37d73207028d2b28c645b5dea7cc39ab5233729 AS kairos-init

FROM almalinux:9@sha256:9b719dc3150c74fd71bd24659b780ec41f5e7166dd24b7d92904125d4f63c65f AS base-kairos

ARG KUBERNETES_DISTRO=k3s
ARG K8S_VERSION_FLAG="--provider-${KUBERNETES_DISTRO}-version"
# renovate: datasource=custom.k3s depName=k3s
ARG KUBERNETES_VERSION=v1.35.4+k3s1
ARG MODEL=generic
ARG TRUSTED_BOOT=false
ARG VERSION

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init \
  -s install \
  --fips \
  -p "${KUBERNETES_DISTRO}" \
  "${K8S_VERSION_FLAG}" "${KUBERNETES_VERSION}" \
  -l debug \
  -m "${MODEL}" \
  -t "${TRUSTED_BOOT}" \
  --version "${VERSION}"


# hadolint ignore=DL3041
RUN dnf update && dnf install -y \
  cifs-utils \
  nmstate \
  python3-pip && \
  dnf clean all

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
  chmod 700 get_helm.sh && \
  HELM_INSTALL_DIR=/usr/bin VERIFY_CHECKSUM=false ./get_helm.sh && \
  rm get_helm.sh

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init \
  -s init \
  --fips \
  -p "${KUBERNETES_DISTRO}" \
  "${K8S_VERSION_FLAG}" "${KUBERNETES_VERSION}" \
  -l debug \
  -m "${MODEL}" \
  -t "${TRUSTED_BOOT}" \
  --version "${VERSION}"

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init validate -t "${TRUSTED_BOOT}"
