FROM quay.io/kairos/kairos-init:v0.10.1@sha256:2225cd2b268937c040b0d325541d6b0685e8af134a5d5f0cf2611069293eaf56 AS kairos-init

FROM almalinux:9@sha256:32468d75602dce128c5dcba6235978cf0fcb43616585699b481c1349fa3fd3e7 AS base-kairos

ARG KUBERNETES_DISTRO=k3s
ARG K8S_VERSION_FLAG="--provider-${KUBERNETES_DISTRO}-version"
# renovate: datasource=custom.k3s depName=k3s
ARG KUBERNETES_VERSION=v1.35.4+k3s1
ARG MODEL=generic
ARG TRUSTED_BOOT=false
ARG VERSION

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init \
  -s install \
  --fips \
  -p "${KUBERNETES_DISTRO}" \
  "${K8S_VERSION_FLAG}" "${KUBERNETES_VERSION}" \
  -l debug \
  -m "${MODEL}" \
  -t "${TRUSTED_BOOT}" \
  --version "${VERSION}"

# hadolint ignore=DL3041
RUN dnf update && dnf install -y \
  cifs-utils \
  nmstate \
  python3-pip && \
  dnf clean all

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
  chmod 700 get_helm.sh && \
  HELM_INSTALL_DIR=/usr/bin VERIFY_CHECKSUM=false ./get_helm.sh && \
  rm get_helm.sh

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init \
  -s init \
  --fips \
  -p "${KUBERNETES_DISTRO}" \
  "${K8S_VERSION_FLAG}" "${KUBERNETES_VERSION}" \
  -l debug \
  -m "${MODEL}" \
  -t "${TRUSTED_BOOT}" \
  --version "${VERSION}"

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init validate -t "${TRUSTED_BOOT}"
