FROM quay.io/kairos/kairos-init:v0.14.1@sha256:69b214bfdf31c01299f364dbeae25ec2c3cee5affb314105f6782cd842671cc7 AS kairos-init

FROM almalinux:9@sha256:d2515c769e7b73f95c4fde38c0a505336ff38f14990c0b7253b77060a049a743 AS base-kairos

ARG KUBERNETES_DISTRO=k3s
ARG K8S_VERSION_FLAG="--provider-${KUBERNETES_DISTRO}-version"
# renovate: datasource=custom.k3s depName=k3s
ARG KUBERNETES_VERSION=v1.35.5+k3s1
ARG MODEL=generic
ARG TRUSTED_BOOT=false
ARG VERSION

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init \
  -s install \
  --fips \
  -p "${KUBERNETES_DISTRO}" \
  "${K8S_VERSION_FLAG}" "${KUBERNETES_VERSION}" \
  -l debug \
  -m "${MODEL}" \
  -t "${TRUSTED_BOOT}" \
  --version "${VERSION}"


# hadolint ignore=DL3041
RUN dnf update && dnf install -y \
  cifs-utils \
  nmstate \
  python3-pip && \
  dnf clean all

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
  chmod 700 get_helm.sh && \
  HELM_INSTALL_DIR=/usr/bin VERIFY_CHECKSUM=false ./get_helm.sh && \
  rm get_helm.sh

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init \
  -s init \
  --fips \
  -p "${KUBERNETES_DISTRO}" \
  "${K8S_VERSION_FLAG}" "${KUBERNETES_VERSION}" \
  -l debug \
  -m "${MODEL}" \
  -t "${TRUSTED_BOOT}" \
  --version "${VERSION}"

# hadolint ignore=DL3059
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init \
  /kairos-init validate -t "${TRUSTED_BOOT}"
