---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: ucl-arc-environments/.github/actions/linting@b6851ba9af3a2ecaae632e6977d05bafb4327063 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
