---
name: Build and publish

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      max-parallel: 1
      matrix:
        distro:
          - almalinux9
          - almalinux10
        k3s_version:
          # renovate: datasource=custom.k3s depName=k3s
          - v1.33.8+k3s1
          # renovate: datasource=custom.k3s depName=k3s
          - v1.34.4+k3s1
          # renovate: datasource=custom.k3s depName=k3s
          - v1.35.1+k3s1

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tag and kairos version
        id: release-tag
        run: |
          distro=${{ matrix.distro }}
          distro_major_version=$(echo ${distro} | grep -oE '[0-9]+')
          kairos_init_version=$(grep "^FROM quay.io/kairos/kairos-init:" images/${distro}/Dockerfile.${distro_major_version} | cut -d':' -f2 | awk -F '[@]' '{print $1}')
          tag="${distro_major_version}-standard-amd64-generic-${kairos_init_version}-k3s${{ matrix.k3s_version }}"
          release_tag="${{ github.event.release.tag_name }}"
          echo "image_tag=${tag//+/-}" >> "$GITHUB_OUTPUT"
          echo "kairos_version=${release_tag}-${distro_major_version}" >> "$GITHUB_OUTPUT"

      - name: Extract tags and labels
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: ${{ env.REGISTRY }}/ucl-arc-environments/kairos-${{ steps.release-tag.outputs.distro }}

      - name: Build and push image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v5
        with:
          context: .
          file: images/${{ steps.release-tag.outputs.distro }}/Dockerfile.${{ steps.release-tag.outputs.distro_major_version }}
          push: true
          tags:
            ${{ env.REGISTRY }}/ucl-arc-environments/kairos-${{ steps.release-tag.outputs.distro }}:${{
            steps.release-tag.outputs.image_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "VERSION=${{ steps.release-tag.outputs.kairos_version }}"
            "KUBERNETES_VERSION=${{ matrix.k3s_version }}"
