---
name: Publish Kairos images

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      max-parallel: 1
      matrix:
        distro:
          - almalinux9
          - almalinux10
        k3s_version:
          # renovate: datasource=custom.k3s depName=k3s_build
          - v1.30.2+k3s1
          # renovate: datasource=custom.k3s depName=k3s_build
          - v1.33.8+k3s1
          # renovate: datasource=custom.k3s depName=k3s_build
          - v1.34.4+k3s1
          # renovate: datasource=custom.k3s depName=k3s_build
          - v1.35.1+k3s1

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tag and kairos version
        id: release-tag
        run: |-
          distro=$(echo ${{matrix.distro}} | grep -oE '[a-zA-Z]+')
          distro_major_version=$(echo ${{matrix.distro}} | grep -oE '[0-9]+')
          kairos_init_version="$(grep "^FROM quay.io/kairos/kairos-init:" "images/${distro}/Dockerfile.${distro_major_version}" | cut -d':' -f2 | awk -F '[@]' '{print $1}')"
          tag="${distro_major_version}-standard-amd64-generic-${kairos_init_version}-k3s${{ matrix.k3s_version }}"
          release_tag="${{ github.event.release.tag_name }}"
          # shellcheck disable=SC2129
          echo "distro=${distro}" >> "$GITHUB_OUTPUT"
          echo "distro_major_version=${distro_major_version}" >> "$GITHUB_OUTPUT"
          echo "image_tag=${tag//+/-}" >> "$GITHUB_OUTPUT"
          echo "kairos_version=${release_tag}-${{matrix.distro}}" >> "$GITHUB_OUTPUT"

      - name: Extract tags and labels
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images:
            ${{ env.REGISTRY }}/ucl-arc-environments/kairos-${{
            steps.release-tag.outputs.distro }}

      - name: Build and push image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: images/${{ steps.release-tag.outputs.distro }}
          file:
            images/${{ steps.release-tag.outputs.distro }}/Dockerfile.${{
            steps.release-tag.outputs.distro_major_version }}
          push: true
          tags:
            ${{ env.REGISTRY }}/ucl-arc-environments/kairos-${{
            steps.release-tag.outputs.distro }}:${{
            steps.release-tag.outputs.image_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "VERSION=${{ steps.release-tag.outputs.kairos_version }}"
            "KUBERNETES_VERSION=${{ matrix.k3s_version }}"
